name: Deployment using kubectl

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Deployment environment (e.g., staging, production)'
        required: true
        type: string
      IMAGE_NAME:
        description: 'Docker image name without TAG'
        required: true
        type: string

    secrets:
      KUBECONFIG:
        description: 'Kubeconfig file content'
        required: true

jobs:
  deploy:
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      NAMESPACE: ${{ vars.NAMESPACE }}
   
    runs-on: github-action-scaleset-demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/
          kubectl version --client

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          kubectl version
          kubectl get nodes

      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Update image in deployment YAML
        run: |
          IMAGE_TAGS="${{ github.run_id }}-${GITHUB_SHA::7}"
          IMAGE="${{ inputs.IMAGE_NAME }}:${IMAGE_TAGS}"

          yq e -i '.spec.template.spec.containers[0].image = strenv(IMAGE)' ./manifests/deployment.yml

          cat ./manifests/deployment.yml

      - name: Create namespace if not exists
        run: |
          kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./manifests/ -n $NAMESPACE

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/vidhya-deployment -n $NAMESPACE
          kubectl get all -n $NAMESPACE
