name: Run Selenium Test 
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Deployment environment (e.g., staging, production)'
        required: true
        type: string

jobs:
  selenium-test:
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: github-action-scaleset-demo
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Run Selenium Tests
        env:
          APP_BASE_URL: ${{ vars.APP_BASE_URL }}  # Base URL of the deployed application for testing
        run: |
          mkdir -p reports
          pytest tests/ --html=reports/selenium_report.html --self-contained-html

      - name: Upload Selenium Test Report
        uses: actions/upload-artifact@v5.0.0

        with:
          name: selenium-test-report
          path: reports/